### ISSUE TITLE
ODE solve gives a truly cryptic error message in cases where it can't prove that the ODE doesn't divide by zero

### ISSUE THREAD

**Issue by bbohrer** [LS-Lab/KeYmaeraX-release#28] opened 2017-03-08 19:21 UTC
e.g.  doing solve on x > 0 & v > 0 & r > 0 |- [{x' = v / r}]x > 0 gives a truly inscrutable error message about not being able to prove some random stuff.

**Comment by nrfulton** [comment] 2017-03-08 19:26
Strange. 

For me at tag 4.3.5 it just proves. Can you give a screenshot or specify a version/commit?

![132_1489001169](https://cloud.githubusercontent.com/assets/1216148/23719945/33d4bf2c-040b-11e7-9ee8-3d14c7b7fe9c.png)

**Comment by nrfulton** [comment] 2017-03-08 19:29
Oh! NVM, you said solve.

Here's the message:

 [Bellerophon Runtime] Dependent position tactic DependentPositionTactic(solve) is not applicable at 1

[Bellerophon Runtime] Could not initialize class edu.cmu.cs.ls.keymaerax.btactics.SimplifierV3$
in >>_<<
at edu.cmu.cs.ls.keymaerax.bellerophon.DependentTactic.computeExpr(BellerophonSyntax.scala:424)
at edu.cmu.cs.ls.keymaerax.bellerophon.AppliedDependentPositionTactic$$anon$1.computeExpr(BellerophonSyntax.scala:518)
at edu.cmu.cs.ls.keymaerax.bellerophon.SequentialInterpreter.apply(SequentialInterpreter.scala:102)
at edu.cmu.cs.ls.keymaerax.bellerophon.SequentialInterpreter.apply(SequentialInterpreter.scala:103)
at edu.cmu.cs.ls.keymaerax.hydra.BellerophonTacticExecutor$$anon$1.call(BellerophonTacticExecutor.scala:129)
at edu.cmu.cs.ls.keymaerax.hydra.BellerophonTacticExecutor$$anon$1.call(BellerophonTacticExecutor.scala:126)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class edu.cmu.cs.ls.keymaerax.btactics.SimplifierV3$
at edu.cmu.cs.ls.keymaerax.btactics.AxiomaticODESolver$.edu$cmu$cs$ls$keymaerax$btactics$AxiomaticODESolver$$simplifier$lzycompute(AxiomaticODESolver.scala:28)
at edu.cmu.cs.ls.keymaerax.btactics.AxiomaticODESolver$.edu$cmu$cs$ls$keymaerax$btactics$AxiomaticODESolver$$simplifier(AxiomaticODESolver.scala:28)
at edu.cmu.cs.ls.keymaerax.btactics.AxiomaticODESolver$$anonfun$axiomaticSolve$1.apply(AxiomaticODESolver.scala:56)
at edu.cmu.cs.ls.keymaerax.btactics.AxiomaticODESolver$$anonfun$axiomaticSolve$1.apply(AxiomaticODESolver.scala:40)
at edu.cmu.cs.ls.keymaerax.btactics.TacticFactory$TacticForNameFactory$$anon$10$$anon$12.computeExpr(MiscTactics.scala:327)
at edu.cmu.cs.ls.keymaerax.bellerophon.SingleGoalDependentTactic.computeExpr(BellerophonSyntax.scala:431)
at edu.cmu.cs.ls.keymaerax.bellerophon.DependentTactic.computeExpr(BellerophonSyntax.scala:419)
... 11 more

**Comment by bbohrer** [comment] 2017-03-08 19:30
BTW I meant to assign this to myself but am too dumb to find the relevant button on GitHub.

The actual case where this came up was more complicated, part of a student's model for Lab 3

**Comment by nrfulton** [comment] 2017-03-08 19:32
Added you. ctrl-F for "assignees" on this page and then click the little gear thingie.

**Comment by bbohrer** [comment] 2017-03-08 19:35
I don't have a gear thingy. Permissions sadness maybe?

**Comment by nrfulton** [comment] 2018-07-13 16:39
@bbohrer did you ever get around to fixing this problem? If so, can you close it? If not, I'll take care of it over the weekend.

**Comment by bbohrer** [comment] 2018-07-13 16:45
Totally can't remember, but I feel like I probably didn't fix it if I left
it open. Maybe git log has info. Would check except floc. Also don't know
if maybe ode stuff has all changed since then?

**Comment by nrfulton** [comment] 2018-07-13 16:59
OK, I'll investigate :-)

**Comment by smitsch** [comment] 2019-05-31 12:32
See 8617f078924b3360b4383d7f464efff5eefe25ee

**Closed by smitsch** 2019-05-31 12:32 UTC
