### ISSUE TITLE
Variables to function

### ISSUE THREAD

**Issue by L-Viard** [LS-Lab/KeYmaeraX-release#71] opened 2020-12-02 11:52 UTC
Hi,
sometimes, when using (differential) cut I have some variables that are automatically converted to function.
The behaviour is the same using either the UI helper or the tactic prompt:
```
cut("vz=(-60)*gamma*(gamma-1)*invDtime")
```
is processed as
```
cut("vz=(-60)*gamma*(gamma-1)*invDtime()")
```
I cannot find any "rule" behind this transformation, at first I suspected it to be linked to the use of interval variables (x >= 10 & x <= 12) but it has been happening with singleton variables too. When the premise can be simplified, first performing a simplification might prevent this transformation. I experienced it with a redundant premise such as
```
x >= 1  + 0.9 * y & y = 10 & x >= 10
```

I should mentionned that after the cut invDtime appears in the definition sub-menu. I tried to expand the definition invDtime() <-> invDtime but a substitution error is raised:
```
Unable to create input tactic 'ANON', cause: Substitution clash:
USubstOne{(invDtime()~>invDtime)}
is not (all)-admissible
for invDtime
when substituting in invDtime()
```

**Comment by bbohrer** [comment] 2020-12-02 13:21
This is done because dI works better with constant functions compared to
variables (it's easier to tell the derivative is zero because the function
is definitely constant). So diffcut makes things constant when it can get
away with it to help out dI later on.

Was this behavior just surprising or was there a proof that you couldn't do
because of it? (I believe there was some change to the "constant-ify" code
recently, but others would know more than me)

**Comment by L-Viard** [comment] 2020-12-02 15:19
Ok, I can see how using functions instead of variables helps the solver. I cannot change the writing as the variables do change between HP. Instead of converting the variable to a function, maybe having a special class of step variable (that cannot continuously evolve) could achieve a similar result, but I cannot estimate the amount of work this would require. I'm not sure whether a rewriting of my model from variable to step functions would work or not (I don't know if conditions work in kyx):
```
Functions
Real x(step) = (step=0 & 0) | (step=1 & 1);
```
using the adequate semantics for BinOp evaluation.

This behaviour is indeed a hindrance for some proofs. I usually end up with something along those lines to prove:
```
x = y  |-  x = y() 
```

**Comment by bbohrer** [comment] 2020-12-02 15:22
Let's wait for some of the other team members to respond, because they want
to check whether all this is just caused by a recent(ly fixed for the next
release) bug

**Comment by smitsch** [comment] 2020-12-03 01:39
The sequent shape `x=y |- x=y()` after (differential) cuts looks indeed like it is caused by the overly eager constification. The new KeYmaera X 4.9.2 should fix this.

**Comment by L-Viard** [comment] 2020-12-03 07:35
Thanks for your answers, it seems to be fixed by kyx 4.9.2
This new version introduces a lot of new things (at least from the GUI point of view, thanks for the diamond differential skip btw !), the diffInvariant especially saves a lot of time !

**Comment by L-Viard** [comment] 2020-12-03 10:23
Actually I happened again.
For a proof, I had to introduce a cut to get the initial value of a variable
```
\exists az0 az = az0
```
After that, making a differencial cut using this initial value convert it as a function
```
dC("az = f(...) + az0")
```
and I end up trying to prove
```
az = az0  |-  az = az0()
```
From my investigation, this conversion depends on the variable: I've tried changing az0 for other trailing variables I still had declared, no conversion occured.

**Comment by smitsch** [comment] 2020-12-04 21:16
I see, the UI infrastructure did not anticipate that new variables can be introduced in the middle of a proof with cuts. The new variable is not recognized until it is constified to az() with dI/dIRule/dIClose. After that, az automatically gets elaborated to az() in subsequent tactic uses. A fix will be included in the next release.

For this specific use case, the old(.) notation in dC is probably more convenient: dC("az = f(...) + old(az)"), which introduces a new discrete ghost automatically.

**Closed** 2021-06-17 10:17 UTC
